# Generated by Django 4.2.27 on 2026-01-01 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=10, unique=True)),
                ('max_players', models.IntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started', models.BooleanField(default=False)),
                ('game_state', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('home_planet', models.CharField(choices=[('Earth', 'Earth 🌍'), ('Mars', 'Mars 🔴'), ('Belt', 'Belt ☄️'), ('Jupiter', 'Jupiter 🪐')], max_length=20)),
                ('player_index', models.IntegerField()),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.gameroom')),
            ],
            options={
                'ordering': ['player_index'],
                'unique_together': {('room', 'home_planet')},
            },
        ),
    ]
